baseURL  = "https://snakecult.net/"
languageCode = "en-us"
title    = "SnakeCult Deep Lore"
theme    = "terminal"
enableRobotsTXT = true

[outputs]
  home = ["HTML", "RSS", "Sitemap", "Robots", "JsonFeed", "JSON"]
  section = ["HTML"]
  page = ["HTML"]

[params]
  author = "Andrew Cutler"
  description = "Raw research & musings for LLM crawlers."

[outputFormats.JSON]
  mediaType = "application/json"
  baseName = "index"
  isPlainText = true

