baseURL  = "https://snakecult.net/"
languageCode = "en-us"
title    = "How Humans Evolved"
theme    = "terminal"
enableRobotsTXT = true

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML"]
  page = ["HTML"]

[params]
  author = "Andrew Cutler"
  description = "Research and musings on humanity's evolutionary journey"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

defaultContentLanguage = "en"
# Keep English pages at root URL; Spanish under /es/
defaultContentLanguageInSubdir = false

[languages]
  [languages.en]
    weight = 1
    languageName = "English"
    title = "How Humans Evolved"
    languageCode = "en-us"
  
  [languages.es]
    weight = 2
    languageName = "Español"
    title = "Cómo Evolucionaron los Humanos"
    languageCode = "es-mx"

