baseURL  = "https://snakecult.net/"
languageCode = "en-us"
title    = "How Humans Evolved"
theme    = "terminal"
enableRobotsTXT = true

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML"]
  page = ["HTML"]

[params]
  author = "Andrew Cutler"
  description = "Research and musings on humanity's evolutionary journey"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

