[languages.es]
disabled = true

[languages.zh]
disabled = true

[languages.fr]
disabled = true

[languages.de]
disabled = true

[languages.pt]
disabled = true

[languages.hi]
disabled = true

[languages.ar]
disabled = true

[languages.ru]
disabled = true 